pipeline {
    agent any

 

    stages {
        stage('Restaurar dependencias') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Compilar') {
            steps {
                sh 'dotnet build --no-restore'
            }
        }

        stage('Pruebas') {
            steps {
                sh 'dotnet test --no-build --verbosity normal'
            }
        }
    }
}
